name: Github Action Practise
on:
  push: 
    branches: 
    - main
    - devlop
    - features/**
  pull_request:
    branches:
    - main
    - devlop
    - features/**
jobs:
  job-1
    My First Job:
    runs-on: Action_Runner
    steps:
    - name: Checkout
    uses: actions/checkout@v6.0.1
    
