name: My Application Pipeline Practise
on: 
  workflow_dispatch:
  # push:
  #   branches: 
  #     - main
  #     - devlop
  #     - features/**
  # pull_request:
  #   branches:
  #     - main
  #     - devlop
  #     - features/**
jobs:
  job-1:
    runs-on: self_hosted
    name: My First Job||||Build
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v6.1.0
      with:
        node-version: 16.x
    - name: Install Dependencies
      run: npm install
    - name: Build Artifacts
      run: npm run build
    
 
        
      
    
  

    
