name: Application Practise
on: 
  workflow_dispatch:
jobs:
  job-1:
    runs-on: self_hosted
    name: My 1st Job||Build
    steps:
    - name: Clean workspace
      run: rm -rf *
    - name: Checkout
      uses: actions/checkout@v6.0.1
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v6.1.0
      with:
        node-version: 16.x
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build Artifacts
      run: npm run build
    
 
        
      
    
  

    
