name: My Application Pipeline Practise
on: 
  workflow_dispatch:
  # push:
  #   branches: 
  #     - main
  #     - devlop
  #     - features/**
  # pull_request:
  #   branches:
  #     - main
  #     - devlop
  #     - features/**
jobs:
  job-1:
    runs-on: self_hosted
    name: My First Job
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.1
    - name: Setup Node.js environment
      uses: actions/setup-node@v6.1.0
      with:
        node-version: 16.x
      
    
  

    
